/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDropsRouteImport } from './routes/admin/drops'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminSettlementRouteImport } from './routes/admin/settlement'
import { Route as AdminTestsRouteImport } from './routes/admin/tests'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'
import { Route as DropsSlugRouteImport } from './routes/drops.$slug'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as TestsIdRouteImport } from './routes/tests.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDropsRoute = AdminDropsRouteImport.update({
  id: '/admin/drops',
  path: '/admin/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettlementRoute = AdminSettlementRouteImport.update({
  id: '/admin/settlement',
  path: '/admin/settlement',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestsRoute = AdminTestsRouteImport.update({
  id: '/admin/tests',
  path: '/admin/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsSlugRoute = DropsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DropsRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const TestsIdRoute = TestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TestsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/desk': typeof DeskRoute
  '/drops': typeof DropsRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRouteWithChildren
  '/tests': typeof TestsRouteWithChildren
  '/admin/drops': typeof AdminDropsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settlement': typeof AdminSettlementRoute
  '/admin/tests': typeof AdminTestsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/drops/$slug': typeof DropsSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/tests/$id': typeof TestsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/desk': typeof DeskRoute
  '/drops': typeof DropsRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRouteWithChildren
  '/tests': typeof TestsRouteWithChildren
  '/admin/drops': typeof AdminDropsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settlement': typeof AdminSettlementRoute
  '/admin/tests': typeof AdminTestsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/drops/$slug': typeof DropsSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/tests/$id': typeof TestsIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/desk': typeof DeskRoute
  '/drops': typeof DropsRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRouteWithChildren
  '/tests': typeof TestsRouteWithChildren
  '/admin/drops': typeof AdminDropsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settlement': typeof AdminSettlementRoute
  '/admin/tests': typeof AdminTestsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/drops/$slug': typeof DropsSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/tests/$id': typeof TestsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/desk'
    | '/drops'
    | '/library'
    | '/login'
    | '/orders'
    | '/profile'
    | '/shop'
    | '/tests'
    | '/admin/drops'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settlement'
    | '/admin/tests'
    | '/admin/users'
    | '/api/telegram'
    | '/drops/$slug'
    | '/orders/$id'
    | '/shop/$slug'
    | '/tests/$id'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/desk'
    | '/drops'
    | '/library'
    | '/login'
    | '/orders'
    | '/profile'
    | '/shop'
    | '/tests'
    | '/admin/drops'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settlement'
    | '/admin/tests'
    | '/admin/users'
    | '/api/telegram'
    | '/drops/$slug'
    | '/orders/$id'
    | '/shop/$slug'
    | '/tests/$id'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/desk'
    | '/drops'
    | '/library'
    | '/login'
    | '/orders'
    | '/profile'
    | '/shop'
    | '/tests'
    | '/admin/drops'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settlement'
    | '/admin/tests'
    | '/admin/users'
    | '/api/telegram'
    | '/drops/$slug'
    | '/orders/$id'
    | '/shop/$slug'
    | '/tests/$id'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DeskRoute: typeof DeskRoute
  DropsRoute: typeof DropsRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ShopRoute: typeof ShopRouteWithChildren
  TestsRoute: typeof TestsRouteWithChildren
  AdminDropsRoute: typeof AdminDropsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettlementRoute: typeof AdminSettlementRoute
  AdminTestsRoute: typeof AdminTestsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drops': {
      id: '/admin/drops'
      path: '/admin/drops'
      fullPath: '/admin/drops'
      preLoaderRoute: typeof AdminDropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settlement': {
      id: '/admin/settlement'
      path: '/admin/settlement'
      fullPath: '/admin/settlement'
      preLoaderRoute: typeof AdminSettlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tests': {
      id: '/admin/tests'
      path: '/admin/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AdminTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops/$slug': {
      id: '/drops/$slug'
      path: '/$slug'
      fullPath: '/drops/$slug'
      preLoaderRoute: typeof DropsSlugRouteImport
      parentRoute: typeof DropsRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/tests/$id': {
      id: '/tests/$id'
      path: '/$id'
      fullPath: '/tests/$id'
      preLoaderRoute: typeof TestsIdRouteImport
      parentRoute: typeof TestsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DropsRouteChildren {
  DropsSlugRoute: typeof DropsSlugRoute
}

const DropsRouteChildren: DropsRouteChildren = {
  DropsSlugRoute: DropsSlugRoute,
}

const DropsRouteWithChildren = DropsRoute._addFileChildren(DropsRouteChildren)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface TestsRouteChildren {
  TestsIdRoute: typeof TestsIdRoute
}

const TestsRouteChildren: TestsRouteChildren = {
  TestsIdRoute: TestsIdRoute,
}

const TestsRouteWithChildren = TestsRoute._addFileChildren(TestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DeskRoute: DeskRoute,
  DropsRoute: DropsRouteWithChildren,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ShopRoute: ShopRouteWithChildren,
  TestsRoute: TestsRouteWithChildren,
  AdminDropsRoute: AdminDropsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettlementRoute: AdminSettlementRoute,
  AdminTestsRoute: AdminTestsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiTelegramRoute: ApiTelegramRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
